# .github/workflows/run-test.yml

name: Run Iframe Scraper Test

on:
  # Izinkan untuk dijalankan manual dari tab Actions
  workflow_dispatch:
  # Jalankan otomatis setiap kali ada push ke branch main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Langkah 3: Install dependencies dari requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Langkah 4: Install browser untuk Playwright
      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium
          
      # Langkah 5: Jalankan skrip pengujian
      # Workflow akan otomatis berhenti dengan status "Failed" jika skrip ini error
      - name: Run test script
        run: python test_iframe_scraper.py
