# .github/workflows/run-advanced-test.yml

name: Run Full Series Scraper Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium
          
      - name: Run advanced test script
        run: python test_full_series_scraper.py
      
      # Menggunakan versi 4 yang sekarang diwajibkan
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: scraper-results
          path: episode_iframes.json
